### PR TITLE
chore: repository governance

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
## Repository governance update

This PR was automatically created by the AVM Team hive-mind using the [grept](https://github.com/Azure/grept) governance tool.

We have detected that some files need updating to meet the AVM governance standards.
Please review and merge with alacrity.

Grept config source: `git::https://github.com/Azure/Azure-Verified-Modules-Grept.git//terraform`

Thanks! The AVM team :heart:

### CODE REVIEW

**Comment by khushal08** [comment]
@matt-FFFFFF Jared has already helped me push this changes. Can we cancel this PR, please?

**Comment by matt-FFFFFF** [comment]
Leave it open and merge your branch. Then we should rebase to see if there are any further changes

**Comment by jaredfholgate** [comment]
Just read Matt's comment, so re-opened and will rebase now.

**Comment by matt-FFFFFF** [comment]
Either or :)

**Pull request merged**
